services:
  python:
    image: python
    build:
      context: .
      dockerfile: dockerfile
      args:
        WORKDIR: /Projects/python-project-starter
    platform: linux/amd64
    volumes:
      - ../../:/Projects/python-project-starter